### PR TITLE
Update 30_Tutorial_Search.asciidoc

### PR DESCRIPTION
**Pull request by OuIChien**

### CODE REVIEW

**Comment by medcl** [comment]
THX，but this change is not necessary

**Comment by mamh2020** [comment]
@medcl why not necessary???

那个搜索的不是改用post请求的吗？

**Comment by medcl** [comment]
搜索是读操作，应该用 GET

**Comment by biyuhao** [comment]
Hi, please refer to https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html
> Both HTTP GET and HTTP POST can be used to execute search with body. Since not all clients support GET with body, POST is allowed as well.

I think we can close this for now. Thanks for the attention :)

**Pull request closed without merging**
