### PR TITLE
the image can't be loaded, fix the image's url.

### PR DESCRIPTION
**Pull request by bluerocly**
When read the doc in github, the images can't be loaded, so change the relative path for the image showing.

### CODE REVIEW

**Comment by medcl** [comment]
编译失败啊，这个 pr

**Comment by bluerocly** [comment]
我看所有图片在githup显示都有问题，我看英文的也是images，没有../，所以只修改了一个，不太确定，没敢大面积修改。

**Comment by chuanchang** [comment]
@medcl how to compile/generate document or run unit test? do we have a guide to show this? thanks in advance.

In addition,  it had better we have CI system to do a basic check then raise failure detail in here.

**Comment by medcl** [comment]
check out the wiki page first, we have discussion group and google sheet to working with this project.

**Pull request merged**
