### PR TITLE
修改译者与审校人员显示样式，Tips表格

### PR DESCRIPTION
**Pull request by MyKings**

### CODE REVIEW

**Comment by medcl** [comment]
Thanks, but this seems not necessary.

**Comment by MyKings** [comment]
@medcl The original translator link is not linked to his github.

**Comment by medcl** [comment]
@MyKings can you show me details, seems good here:
https://www.elastic.co/guide/cn/elasticsearch/guide/current/_acknowledgments.html

**Comment by MyKings** [comment]
https://github.com/elasticsearch-cn/elasticsearch-definitive-guide/blob/cn/Preface.asciidoc 
github

Looking at github is a small problem, I decided to turn this pr off.

**Pull request closed without merging**
